package config

// 协议定义
const (
	MESSAGE_ID_JOIN_ROOM_REQUEST  = 1 // 加入房间请求
	MESSAGE_ID_JOIN_ROOM_RESPONSE = 2 // 加入房间回应
	MESSAGE_ID_JOIN_ROOM_PUSH     = 3 // 加入房间推送
	MESSAGE_ID_QUIT_ROOM_REQUEST  = 4 // 退出房间请求
	MESSAGE_ID_QUIT_ROOM_RESPONSE = 5 // 退出房间回应
	MESSAGE_ID_QUIT_ROOM_PUSH     = 6 // 退出房间推送

	MESSAGE_ID_PRIVATE_MESSAGE_REQUEST    = 101 // 私聊消息请求
	MESSAGE_ID_PRIVATE_MESSAGE_RESPONSE   = 102 // 私聊消息回应
	MESSAGE_ID_PRIVATE_MESSAGE_NOTIFY     = 103 // 私聊消息通知(暂未支持)
	MESSAGE_ID_PRIVATE_MESSAGE_PUSH       = 104 // 私聊消息推送
	MESSAGE_ID_ROOM_MESSAGE_REQUEST       = 105 // 房间消息请求
	MESSAGE_ID_ROOM_MESSAGE_RESPONSE      = 106 // 房间消息回应
	MESSAGE_ID_ROOM_MESSAGE_NOTIFY        = 107 // 房间消息通知(暂未支持)
	MESSAGE_ID_ROOM_MESSAGE_PUSH          = 108 // 房间消息推送
	MESSAGE_ID_BROADCAST_MESSAGE_REQUEST  = 109 // 广播消息请求
	MESSAGE_ID_BROADCAST_MESSAGE_RESPONSE = 110 // 广播消息回应
	MESSAGE_ID_BROADCAST_MESSAGE_NOTIFY   = 111 // 广播消息通知(暂未支持)
	MESSAGE_ID_BROADCAST_MESSAGE_PUSH     = 112 // 广播消息推送
)
